version: "3.9"

services:
  rabbitmq:
    image: "rabbitmq:3.11.23"
    ports:
      - "81:15672"
    expose:
      - 5672
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}

  postgres_users:
    image: toys-store/postgres-users
    build: ./users/postgres-docker
    expose:
      - 5432
    hostname: postgres_users
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  users:
    image: toys-store/users
    build: ./users
    depends_on:
      - postgres_users
      - rabbitmq
    ports:
      - "8082:8080"
  postgres_items:
    image: toys-store/postgres-items
    build: ./items/postgres-docker
    expose:
      - 5432
    hostname: postgres_items
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  items:
    image: toys-store/items
    build: ./items
    depends_on:
      - postgres_items
      - rabbitmq
    hostname: items
    ports:
      - "8083:8080"
  postgres_carts:
    image: toys-store/postgres-carts
    build: ./carts/postgres-docker
    expose:
      - 5432
    hostname: postgres_carts
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  carts:
    image: toys-store/carts
    build: ./carts
    depends_on:
      - postgres_carts
      - rabbitmq
    ports:
      - "8084:8080"
    networks:
      - default
      - ditto_default
  postgres_stores:
    image: toys-store/postgres-stores
    build: ./stores/postgres-docker
    expose:
      - 5432
    hostname: postgres_stores
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  stores:
    image: toys-store/stores
    build: ./stores
    depends_on:
      - postgres_stores
      - rabbitmq
    ports:
      - "8085:8080"
    networks:
      - default
      - ditto_default
  postgres_shopping:
    image: toys-store/postgres-shopping
    build: ./shopping/postgres-docker
    expose:
      - 5432
    hostname: postgres_shopping
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  shopping:
    image: toys-store/shopping
    build: ./shopping
    depends_on:
      - postgres_shopping
      - rabbitmq
    ports:
      - "8086:8080"
  postgres_payments:
    image: toys-store/postgres-payments
    build: ./payments/postgres-docker
    expose:
      - 5432
    hostname: postgres_payments
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  payments:
    image: toys-store/payments
    build: ./payments
    depends_on:
      - postgres_payments
      - rabbitmq
    ports:
      - "8087:8080"

networks:
  ditto_default:
    name: ditto_default
    external: true
